### ISSUE TITLE
How to Run migration command remotely with the Heroku Postgres connection string ?

### ISSUE THREAD

**Issue by natheeshsunway** [jeremymaya/herokufy-dotnet#7]

**Comment by jeremymaya** [comment]
Running migration command with entity framework core should be same regardless of which database you choose to use or where your database is running from. 

Please take a look at the following doc to learn how to run the migration command. 

https://gist.github.com/jeremymaya/a36c1de8220d76beca85a2804a2cecc4#migration-and-update

**Comment by jeremymaya** [comment]
The official documentation from Microsoft is also extremely helpful:

https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli

**Comment by natheeshsunway** [comment]
Thanks for replying @jeremymaya , Is it possible to run the migration command on docker?

**Comment by jeremymaya** [comment]
The migration command should work for projects connected to databases running on docker

**Comment by natheeshsunway** [comment]
You are saying like when our dotnet connected with new heruko postgres, it will automatically run the migration script, when connection created... is I am telling right?

**Comment by jeremymaya** [comment]
I have not tried creating a migration script that auto executes 😮

If you are using Visual Studio 2019, and only has one database for the project, you can use the Package Manager Console tool to run the following commands:

```bash
Add-Migration InitialCreate
```

```bash
Update-Database
```
That should create a database on Heroku Postgres if the connection string is pointing to Heroku Postgres.

**Comment by jeremymaya** [comment]
Also understand that Entity Framework Core migration command is used to [create a database from the model](https://docs.microsoft.com/en-us/ef/core/) - This means that the docker has nothing to do with deploying a database in this process.

You are running the migration command to deploy a database based on your code before running the app in docker environment.

**Comment by natheeshsunway** [comment]
Yes... You are right... Thanks for helping.
